### ISSUE TITLE
Storage issue for images and videos

### ISSUE THREAD

**Issue by kaipartmann** [kaipartmann/Peridynamics.jl#147]
This is a permanently closed storage issue for images and videos used in the documentation of the package.
If they would be stored inside the `docs/src/assets` directory, every time a user `add`s the package, all these files are downloaded on their system. To make the repo smaller in size, these images should instead be dropped inside this issue, one image at a time. This will create a unique url to this file that then can be used to add the image.

**Comment by kaipartmann** [comment]
<img width="562" alt="PDBody" src="https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/728da1f0-4750-4ab6-a430-9b206e475577">

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/728da1f0-4750-4ab6-a430-9b206e475577
```

**Comment by kaipartmann** [comment]
<img width="575" alt="PD_OneNI_1" src="https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/0380b1b8-4527-4f38-a20e-435a6f1c8ba1">

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/0380b1b8-4527-4f38-a20e-435a6f1c8ba1
```

**Comment by kaipartmann** [comment]
![OberflaechenEffekt_3](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/b899c8d3-e358-4d4d-b52f-13b6c0af747b)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/b899c8d3-e358-4d4d-b52f-13b6c0af747b
```

**Comment by kaipartmann** [comment]
<img width="531" alt="PD_TwoNI_1" src="https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/5b340634-7c3f-4ddf-a056-06c31564077c">

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/5b340634-7c3f-4ddf-a056-06c31564077c
```

**Comment by kaipartmann** [comment]
<img width="529" alt="PD_ThreeNI_1" src="https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/e908c804-a6d4-4bf6-b75a-988f33989213">

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/e908c804-a6d4-4bf6-b75a-988f33989213
```

**Comment by kaipartmann** [comment]
<img width="914" alt="ParaViewTutorial1" src="https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/a5cfb0f2-db8a-4c3b-9f9e-6fc1c66b3716">

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/a5cfb0f2-db8a-4c3b-9f9e-6fc1c66b3716
```

**Comment by kaipartmann** [comment]
<img width="1275" alt="ParaViewTutorial2" src="https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/32246ca6-548d-4883-87e0-c9fb88baffd4">
```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/32246ca6-548d-4883-87e0-c9fb88baffd4
```

**Comment by kaipartmann** [comment]
<img width="1275" alt="ParaViewTutorial3" src="https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/78c618e8-0a3b-455c-a1f7-707079714479">

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/78c618e8-0a3b-455c-a1f7-707079714479
```

**Comment by kaipartmann** [comment]
<img width="1275" alt="ParaViewTutorial4" src="https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/484cdf0a-16ac-4c64-b2b4-9ad96ca6c817">

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/484cdf0a-16ac-4c64-b2b4-9ad96ca6c817
```

**Comment by kaipartmann** [comment]
<img width="1275" alt="ParaViewTutorial5" src="https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/7a38a834-1157-469b-9b79-3c3b24388c39">

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/7a38a834-1157-469b-9b79-3c3b24388c39
```

**Comment by kaipartmann** [comment]
![TensileTestMesh](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/d2f333d4-ffa5-4227-aed9-542d49298c01)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/d2f333d4-ffa5-4227-aed9-542d49298c01
```

**Comment by kaipartmann** [comment]
![tutorial_tension_dynfrac_last_step](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/dda2b7b3-d44b-41a9-b133-6d1b548df1c1)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/dda2b7b3-d44b-41a9-b133-6d1b548df1c1
```

**Comment by kaipartmann** [comment]
![2024-07-06_01-32_fps-30](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/fcd71bd7-f6ef-4f72-97c2-27ddd2acbf89)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/fcd71bd7-f6ef-4f72-97c2-27ddd2acbf89
```

**Comment by kaipartmann** [comment]
![tutorial_tension_static_last_step](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/11dd6107-12fa-4ccc-9083-629ee057d788)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/11dd6107-12fa-4ccc-9083-629ee057d788
```

**Comment by kaipartmann** [comment]
![2024-07-06_01-51_fps-30](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/d74d60fb-c792-4d5b-a683-9448d6c92e83)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/d74d60fb-c792-4d5b-a683-9448d6c92e83
```

**Comment by kaipartmann** [comment]
![tutorial_tension_1](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/ca3e724b-9dd7-417a-b3aa-bc37f81f4674)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/ca3e724b-9dd7-417a-b3aa-bc37f81f4674
```

**Comment by kaipartmann** [comment]
![tutorial_tension_2](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/36a16d3e-a2a5-4db7-9b73-55b321583902)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/36a16d3e-a2a5-4db7-9b73-55b321583902
```

**Comment by kaipartmann** [comment]
![tutorial_tension_3](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/7c3e0b71-57b7-4bff-9bca-617bdae9f5be)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/7c3e0b71-57b7-4bff-9bca-617bdae9f5be
```

**Comment by kaipartmann** [comment]
![tension_precrack_damage](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/9dd6b70e-46de-48c7-ad46-c2970cb150a2)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/9dd6b70e-46de-48c7-ad46-c2970cb150a2
```

**Comment by kaipartmann** [comment]
![2024-07-06_02-48_fps-30](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/0f78a13a-7497-4218-a254-45d936df9602)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/0f78a13a-7497-4218-a254-45d936df9602
```

**Comment by kaipartmann** [comment]
![Peridynamics](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/56648a2d-9d5a-4b99-94bf-10570affa113)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/56648a2d-9d5a-4b99-94bf-10570affa113
```

**Comment by kaipartmann** [comment]
![Peridynamics_dark](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/817c7bd4-9c02-4cc4-ac66-998c0f5e95e2)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/817c7bd4-9c02-4cc4-ac66-998c0f5e95e2
```

**Comment by kaipartmann** [comment]
![kalthoff_winkler_last_timestep](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/6dc362ef-4997-4327-9bc1-41350fac2dc1)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/6dc362ef-4997-4327-9bc1-41350fac2dc1
```

**Comment by kaipartmann** [comment]
![kw](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/ba21d9d1-4fc3-4894-8842-65c835506463)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/ba21d9d1-4fc3-4894-8842-65c835506463
```

**Comment by kaipartmann** [comment]
![old_logo](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/5439e112-9088-49a3-bb01-aff541adc0f8)

# the old logo
```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/5439e112-9088-49a3-bb01-aff541adc0f8
```

**Comment by kaipartmann** [comment]
![old_logo](https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/b79fd475-67fc-4097-9f05-791833f29fa9)

```
https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/b79fd475-67fc-4097-9f05-791833f29fa9
```

**Comment by kaipartmann** [comment]
![falling_glass](https://github.com/user-attachments/assets/e953c31a-c4f8-4889-8e5e-03ee81e6dc4b)

```
https://github.com/user-attachments/assets/e953c31a-c4f8-4889-8e5e-03ee81e6dc4b
```

**Comment by kaipartmann** [comment]
https://github.com/user-attachments/assets/b6b2ba41-1ed3-497f-b496-44655d4be696

```
https://github.com/user-attachments/assets/b6b2ba41-1ed3-497f-b496-44655d4be696
```

**Comment by kaipartmann** [comment]
https://github.com/user-attachments/assets/332babb0-5c6f-4ae0-89e8-3ae1a7a80177

```
https://github.com/user-attachments/assets/332babb0-5c6f-4ae0-89e8-3ae1a7a80177
```

**Comment by kaipartmann** [comment]
https://github.com/user-attachments/assets/918aed7b-735d-418f-900c-e0a996db2bab

```
https://github.com/user-attachments/assets/918aed7b-735d-418f-900c-e0a996db2bab
```

**Comment by kaipartmann** [comment]
https://github.com/user-attachments/assets/49aca8fe-cbe8-4e5a-8a78-02ce4aeb3cae

```
https://github.com/user-attachments/assets/49aca8fe-cbe8-4e5a-8a78-02ce4aeb3cae
```

**Comment by kaipartmann** [comment]
https://github.com/user-attachments/assets/0761ba02-f69a-4f3a-b5c5-0f219548070f

```
https://github.com/user-attachments/assets/0761ba02-f69a-4f3a-b5c5-0f219548070f
```

**Comment by kaipartmann** [comment]
![last_step_anim1](https://github.com/user-attachments/assets/58e11123-6143-4e13-8642-7e30c9e6c86d)

```
https://github.com/user-attachments/assets/58e11123-6143-4e13-8642-7e30c9e6c86d
```

**Comment by kaipartmann** [comment]
https://github.com/user-attachments/assets/a2594777-5d0b-4c5a-acd4-da1e357a06e3

```
https://github.com/user-attachments/assets/a2594777-5d0b-4c5a-acd4-da1e357a06e3
```

**Comment by kaipartmann** [comment]
![long_bar_v_with_v_t](https://github.com/user-attachments/assets/34165b09-2df9-495d-8e41-acff28d0098c)

```
https://github.com/user-attachments/assets/34165b09-2df9-495d-8e41-acff28d0098c
```

**Comment by kaipartmann** [comment]
![logo](https://github.com/user-attachments/assets/1903c83d-072e-4d50-a575-293d03bb7a94)
```
https://github.com/user-attachments/assets/1903c83d-072e-4d50-a575-293d03bb7a94
```

**Comment by mdienst** [comment]
<img width="748" alt="image" src="https://github.com/user-attachments/assets/3a236222-ef75-44fc-921d-c2d4231c33ec">

https://github.com/user-attachments/assets/3a236222-ef75-44fc-921d-c2d4231c33ec

**Comment by mdienst** [comment]
https://github.com/user-attachments/assets/d7e600ee-cad8-40f9-99f4-e96ac05585d6

```
https://github.com/user-attachments/assets/d7e600ee-cad8-40f9-99f4-e96ac05585d6
```

**Comment by mdienst** [comment]
![preview](https://github.com/user-attachments/assets/91bfd2df-158d-4455-8285-06898639a619)

```
https://github.com/user-attachments/assets/91bfd2df-158d-4455-8285-06898639a619
```

**Comment by kaipartmann** [comment]
![long_bar_v_with_v_t_stacked](https://github.com/user-attachments/assets/7fa65fd4-38d8-46cb-833f-990417211d17)
```
https://github.com/user-attachments/assets/7fa65fd4-38d8-46cb-833f-990417211d17
```

**Comment by mdienst** [comment]
![bb_uniform2 0124](https://github.com/user-attachments/assets/47196703-09e9-40c0-8742-10396762a4f1)

```
https://github.com/user-attachments/assets/47196703-09e9-40c0-8742-10396762a4f1
```

**Comment by kaipartmann** [comment]
![TutorialOverview](https://github.com/user-attachments/assets/f69ec7f5-2deb-4328-bfab-05cc15508af2)
```
https://github.com/user-attachments/assets/f69ec7f5-2deb-4328-bfab-05cc15508af2
```

**Comment by mdienst** [comment]
https://github.com/user-attachments/assets/b9839787-f265-43f4-9d57-a33375ad9610

```
https://github.com/user-attachments/assets/b9839787-f265-43f4-9d57-a33375ad9610
```

**Comment by mdienst** [comment]
https://github.com/user-attachments/assets/45513e03-fde0-44ad-ac90-ca181d59933c

```
https://github.com/user-attachments/assets/45513e03-fde0-44ad-ac90-ca181d59933c
```

**Comment by mdienst** [comment]
https://github.com/user-attachments/assets/91a274dc-7e45-4a21-9283-414b86199e48

```
https://github.com/user-attachments/assets/91a274dc-7e45-4a21-9283-414b86199e48
```

**Comment by mdienst** [comment]
https://github.com/user-attachments/assets/dea25e90-34e1-4faf-9241-a5161a741c68

```
https://github.com/user-attachments/assets/dea25e90-34e1-4faf-9241-a5161a741c68
```

**Comment by mdienst** [comment]
<img width="837" alt="Image" src="https://github.com/user-attachments/assets/86caad93-8a56-495b-822a-ffccc5c43c9e" />
```
https://github.com/user-attachments/assets/86caad93-8a56-495b-822a-ffccc5c43c9e
```

**Comment by mdienst** [comment]
<img width="434" alt="Image" src="https://github.com/user-attachments/assets/79340f51-cb62-42b2-8f1b-fd474f7fe8fb" />

```
https://github.com/user-attachments/assets/79340f51-cb62-42b2-8f1b-fd474f7fe8fb
```

**Comment by mdienst** [comment]
<img width="461" alt="Image" src="https://github.com/user-attachments/assets/34434920-a758-438a-a463-a259397f1bba" />

```
https://github.com/user-attachments/assets/34434920-a758-438a-a463-a259397f1bba
```

**Comment by mdienst** [comment]
<img width="458" alt="Image" src="https://github.com/user-attachments/assets/6265e5b8-bff5-4aa3-83b7-62a385578f37" />

```
https://github.com/user-attachments/assets/6265e5b8-bff5-4aa3-83b7-62a385578f37
```

**Comment by mdienst** [comment]
<img width="858" alt="Image" src="https://github.com/user-attachments/assets/c2cd75de-065e-4568-abde-e753216f3e85" />

```
https://github.com/user-attachments/assets/c2cd75de-065e-4568-abde-e753216f3e85
```

**Comment by mdienst** [comment]
<img width="326" alt="Image" src="https://github.com/user-attachments/assets/ab389e50-05f7-4d6e-8b0d-992fb6c79a75" />

```
https://github.com/user-attachments/assets/ab389e50-05f7-4d6e-8b0d-992fb6c79a75
```

**Comment by kaipartmann** [comment]
<img width="1200" height="1200" alt="Image" src="https://github.com/user-attachments/assets/aae0ca8a-6c3a-4074-b91a-9317fd2bf2f9" />

```
https://github.com/user-attachments/assets/aae0ca8a-6c3a-4074-b91a-9317fd2bf2f9
```
