### ISSUE TITLE
JuliaPDE?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [kaipartmann/Peridynamics.jl#15]
Interested in getting this repo included? A PR or an issue would be welcome...

**Comment by PetrKryslUCSD** [comment]
https://discourse.julialang.org/t/psa-thread-local-state-is-no-longer-recommended-common-misconceptions-about-threadid-and-nthreads/101274/9

**Comment by kaipartmann** [comment]
Thanks, @PetrKryslUCSD, for pointing out this very useful repo! I gladly accept your offer and already made a PR.
https://github.com/JuliaPDE/SurveyofPDEPackages/pull/41.
