### ISSUE TITLE
[ENHANCEMENT] Clarification on pre-cracked surfaces

### ISSUE THREAD

**Issue by oldninja** [kaipartmann/Peridynamics.jl#31]
---
name: 💡 Enhancement Request
about: Request an enhancement or clarification on pre-cracked surfaces
title: '[ENHANCEMENT] Clarification on pre-cracked surfaces'

---

### Requested Enhancement/Clarification:

1) First, thank you, @kaipartmann, for putting together such a nice and well-written peridynamic implementation.
2) I would like to better understand the pre-crack option per the example on [tutorial_tension_precrack](https://kaipartmann.github.io/Peridynamics.jl/stable/generated/tutorial_tension_precrack/):
I noticed that the pre-cracked area gets a damage value when initially placed. Say the damage variable equals 0.5 on the nodes at the edge and less towards the inner portion of the body. However, I believe the pre-cracked surfaces should be "undamaged" at the beginning of the simulation. The only difference with respect to the other neighbors is that these nodes on the crack surfaces have fewer neighbors compared to the bulk of the material. Is this how it is intended to be (as-is)?

### Anything else:

[tutorial_tension_precrack](https://kaipartmann.github.io/Peridynamics.jl/stable/generated/tutorial_tension_precrack/)

---

**Comment by oldninja** [comment]
I think that is an elegant solution. I could try to help in the implementation if you point me in the right direction. I couldn't quickly find where to effectively change the precrack! function.

**Comment by kaipartmann** [comment]
Thank you very much @oldninja for your offer to contribute!
Unfortunately, I struggled to point you in the right direction and to consider how this could be implemented. The internal structure has yet to be finalized, so  I ended up restructuring half of the package and added the feature during that process.

I talked to my students working with the package, and they preferred the standard setting `update_dmg=true`. Maybe this will change, but I will keep it that way for now.

You can try it out with this code:
```julia
using Peridynamics
l, Δx, δ, a = 1.0, 1/50, 3.015/50, 0.5
pos, vol = uniform_box(l, l, 0.1l, Δx)
b = Body(BBMaterial(), pos, vol)
material!(b; horizon=3.015Δx, E=2.1e5, rho=8e-6, Gc=2.7)
point_set!(p -> p[1] ≤ -l/2+a && 0 ≤ p[2] ≤ 2δ, b, :set_a)
point_set!(p -> p[1] ≤ -l/2+a && -2δ ≤ p[2] < 0, b, :set_b)
precrack!(b, :set_a, :set_b; update_dmg=false)
point_set!(p -> p[2] > l/2-Δx, b, :set_top)
point_set!(p -> p[2] < -l/2+Δx, b, :set_bottom)
velocity_bc!(t -> -30, b, :set_bottom, :y)
velocity_bc!(t -> 30, b, :set_top, :y)
vv = VelocityVerlet(steps=2000)
job = Job(b, vv; path=joinpath("results", "mode_I"))
submit(job);
```
<img width="931" alt="mode_I" src="https://github.com/kaipartmann/Peridynamics.jl/assets/68582683/7743ece8-c7a6-4f5f-86c9-f4636e206d89">

Keep in mind that you have to install the current state of the main branch:
```
pkg> add Peridynamics#main
```
